@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#queryMessage(String,String,int,long,long)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1714486248 { 
   	label=rocketmq
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1314323680 { 
   	label=MQAdminImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   MQAdminImpl1527982467XXXqueryMessage2049666629[
	label="+ queryMessage()"
	style=filled
	fillcolor=white
	tooltip="MQAdminImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1350583147 { 
   	label=Slf4jLogger
	labeljust=l
	fillcolor=white
	style=filled
   
   Slf4jLogger2118845798XXXerror424332965[
	label="+ error()"
	style=filled
	fillcolor=white
	tooltip="Slf4jLogger

null"
	fontcolor=darkgreen
];

Slf4jLogger2118845798XXXwarn1506910935[
	label="+ warn()"
	style=filled
	fillcolor=white
	tooltip="Slf4jLogger

null"
	fontcolor=darkgreen
];

Slf4jLogger2118845798XXXwarn1808118735[
	label="+ warn()"
	style=filled
	fillcolor=white
	tooltip="Slf4jLogger

null"
	fontcolor=darkgreen
];

Slf4jLogger2118845798XXXwarn1881684228[
	label="+ warn()"
	style=filled
	fillcolor=white
	tooltip="Slf4jLogger

null"
	fontcolor=darkgreen
];

Slf4jLogger2118845798XXXwarn424332965[
	label="+ warn()"
	style=filled
	fillcolor=white
	tooltip="Slf4jLogger

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1817307469 { 
   	label=MQClientInstance
	labeljust=l
	fillcolor=white
	style=filled
   
   MQClientInstance700434529XXXgetAnExistTopicRouteData1808118735[
	label="+ getAnExistTopicRouteData()"
	style=filled
	fillcolor=white
	tooltip="MQClientInstance

null"
	fontcolor=darkgreen
];

MQClientInstance700434529XXXupdateTopicRouteInfoFromNameServer1808118735[
	label="+ updateTopicRouteInfoFromNameServer()"
	style=filled
	fillcolor=white
	tooltip="MQClientInstance

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1833644171 { 
   	label=InnerLogger
	labeljust=l
	fillcolor=white
	style=filled
   
   InnerLogger1066893677XXXerror424332965[
	label="+ error()"
	style=filled
	fillcolor=white
	tooltip="InnerLogger

null"
	fontcolor=darkgreen
];

InnerLogger1066893677XXXwarn1506910935[
	label="+ warn()"
	style=filled
	fillcolor=white
	tooltip="InnerLogger

null"
	fontcolor=darkgreen
];

InnerLogger1066893677XXXwarn1808118735[
	label="+ warn()"
	style=filled
	fillcolor=white
	tooltip="InnerLogger

null"
	fontcolor=darkgreen
];

InnerLogger1066893677XXXwarn1881684228[
	label="+ warn()"
	style=filled
	fillcolor=white
	tooltip="InnerLogger

null"
	fontcolor=darkgreen
];

InnerLogger1066893677XXXwarn424332965[
	label="+ warn()"
	style=filled
	fillcolor=white
	tooltip="InnerLogger

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2004609280 { 
   	label=DefaultMQPushConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumer633216551XXXqueryMessage2049666629[
	label="+ queryMessage()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumer

&#10;  This method will be removed in a certain version after April 5, 2020, so please do not use this method.&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_290650472 { 
   	label=DefaultMQPushConsumerImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumerImpl1317777407XXXqueryMessage2049666629[
	label="+ queryMessage()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumerImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_454799875 { 
   	label=RemotingCommand
	labeljust=l
	fillcolor=white
	style=filled
   
   RemotingCommand1388817347XXXdecodeCommandCustomHeader831959679[
	label="+ decodeCommandCustomHeader()"
	style=filled
	fillcolor=white
	tooltip="RemotingCommand

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_925786939 { 
   	label=BrokerData
	labeljust=l
	fillcolor=white
	style=filled
   
   BrokerData846711030XXXselectBrokerAddr0[
	label="+ selectBrokerAddr()"
	style=filled
	fillcolor=white
	tooltip="BrokerData

&#10;  Selects a (preferably master) broker address from the registered list.&#10;  If the master's address cannot be found, a slave broker address is selected in a random manner.&#10; &#10;  @return Broker address.&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_931339104 { 
   	label=MQClientAPIImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   MQClientAPIImpl1527982467XXXqueryMessage676714341[
	label="+ queryMessage()"
	style=filled
	fillcolor=white
	tooltip="MQClientAPIImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_966143399 { 
   	label=MessageDecoder
	labeljust=l
	fillcolor=white
	style=filled
   
   MessageDecoder1295052772XXXdecodes83608148[
	label="+ decodes()"
	style=filled
	fillcolor=white
	tooltip="MessageDecoder

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
DefaultMQPushConsumer633216551XXXqueryMessage2049666629 -> DefaultMQPushConsumerImpl1317777407XXXqueryMessage2049666629;
DefaultMQPushConsumerImpl1317777407XXXqueryMessage2049666629 -> MQAdminImpl1527982467XXXqueryMessage2049666629;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> BrokerData846711030XXXselectBrokerAddr0;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> InnerLogger1066893677XXXerror424332965;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> InnerLogger1066893677XXXwarn1506910935;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> InnerLogger1066893677XXXwarn1808118735;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> InnerLogger1066893677XXXwarn1881684228;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> InnerLogger1066893677XXXwarn424332965;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> MQClientAPIImpl1527982467XXXqueryMessage676714341;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> MQClientInstance700434529XXXgetAnExistTopicRouteData1808118735;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> MQClientInstance700434529XXXupdateTopicRouteInfoFromNameServer1808118735;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> MessageDecoder1295052772XXXdecodes83608148;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> RemotingCommand1388817347XXXdecodeCommandCustomHeader831959679;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> Slf4jLogger2118845798XXXerror424332965;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> Slf4jLogger2118845798XXXwarn1506910935;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> Slf4jLogger2118845798XXXwarn1808118735;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> Slf4jLogger2118845798XXXwarn1881684228;
MQAdminImpl1527982467XXXqueryMessage2049666629 -> Slf4jLogger2118845798XXXwarn424332965;
    
}
@enduml