@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#viewMessage(String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1714486248 { 
   	label=rocketmq
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1314323680 { 
   	label=MQAdminImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   MQAdminImpl1527982467XXXviewMessage1808118735[
	label="+ viewMessage()"
	style=filled
	fillcolor=white
	tooltip="MQAdminImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2004609280 { 
   	label=DefaultMQPushConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumer633216551XXXviewMessage1808118735[
	label="+ viewMessage()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumer

&#10;  This method will be removed in a certain version after April 5, 2020, so please do not use this method.&#10; "
	penwidth=4
	fontcolor=darkgreen
];

DefaultMQPushConsumer633216551XXXviewMessage2013066710[
	label="+ viewMessage()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumer

&#10;  This method will be removed in a certain version after April 5, 2020, so please do not use this method.&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_290650472 { 
   	label=DefaultMQPushConsumerImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumerImpl1317777407XXXviewMessage1808118735[
	label="+ viewMessage()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumerImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_480863395 { 
   	label=RemotingUtil
	labeljust=l
	fillcolor=white
	style=filled
   
   RemotingUtil627545558XXXsocketAddress2String159223009[
	label="+ socketAddress2String()"
	style=filled
	fillcolor=white
	tooltip="RemotingUtil

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_931339104 { 
   	label=MQClientAPIImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   MQClientAPIImpl1527982467XXXviewMessage443628177[
	label="+ viewMessage()"
	style=filled
	fillcolor=white
	tooltip="MQClientAPIImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_966143399 { 
   	label=MessageDecoder
	labeljust=l
	fillcolor=white
	style=filled
   
   MessageDecoder1295052772XXXdecodeMessageId1808118735[
	label="+ decodeMessageId()"
	style=filled
	fillcolor=white
	tooltip="MessageDecoder

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
DefaultMQPushConsumer633216551XXXviewMessage1808118735 -> DefaultMQPushConsumerImpl1317777407XXXviewMessage1808118735;
DefaultMQPushConsumer633216551XXXviewMessage2013066710 -> DefaultMQPushConsumer633216551XXXviewMessage1808118735;
DefaultMQPushConsumerImpl1317777407XXXviewMessage1808118735 -> MQAdminImpl1527982467XXXviewMessage1808118735;
MQAdminImpl1527982467XXXviewMessage1808118735 -> MQClientAPIImpl1527982467XXXviewMessage443628177;
MQAdminImpl1527982467XXXviewMessage1808118735 -> MessageDecoder1295052772XXXdecodeMessageId1808118735;
MQAdminImpl1527982467XXXviewMessage1808118735 -> RemotingUtil627545558XXXsocketAddress2String159223009;
    
}
@enduml