@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#setPullThresholdSizeForQueue(int)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1714486248 { 
   	label=rocketmq
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_2004609280 { 
   	label=DefaultMQPushConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumer633216551XXXsetPullThresholdSizeForQueue104431[
	label="+ setPullThresholdSizeForQueue()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumer

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_393429060 { 
   	label=RebalanceImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   RebalanceImpl1317777407XXXdoRebalance64711720[
	label="+ doRebalance()"
	style=filled
	fillcolor=white
	tooltip="RebalanceImpl

null"
	fontcolor=darkgreen
];

RebalanceImpl1317777407XXXmessageQueueChanged1980240305[
	label="+ messageQueueChanged()"
	style=filled
	fillcolor=white
	tooltip="RebalanceImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_741238794 { 
   	label=RebalancePushImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   RebalancePushImpl1317777407XXXmessageQueueChanged1980240305[
	label="+ messageQueueChanged()"
	style=filled
	fillcolor=white
	tooltip="RebalancePushImpl

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
RebalanceImpl1317777407XXXdoRebalance64711720 -> RebalanceImpl1317777407XXXmessageQueueChanged1980240305;
RebalanceImpl1317777407XXXmessageQueueChanged1980240305 -> RebalancePushImpl1317777407XXXmessageQueueChanged1980240305;
RebalancePushImpl1317777407XXXmessageQueueChanged1980240305 -> DefaultMQPushConsumer633216551XXXsetPullThresholdSizeForQueue104431;
    
}
@enduml