@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#earliestMsgStoreTime(MessageQueue)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1714486248 { 
   	label=rocketmq
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1314323680 { 
   	label=MQAdminImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   MQAdminImpl1527982467XXXearliestMsgStoreTime1134663318[
	label="+ earliestMsgStoreTime()"
	style=filled
	fillcolor=white
	tooltip="MQAdminImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1817307469 { 
   	label=MQClientInstance
	labeljust=l
	fillcolor=white
	style=filled
   
   MQClientInstance700434529XXXfindBrokerAddressInPublish1808118735[
	label="+ findBrokerAddressInPublish()"
	style=filled
	fillcolor=white
	tooltip="MQClientInstance

null"
	fontcolor=darkgreen
];

MQClientInstance700434529XXXupdateTopicRouteInfoFromNameServer1808118735[
	label="+ updateTopicRouteInfoFromNameServer()"
	style=filled
	fillcolor=white
	tooltip="MQClientInstance

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_192096112 { 
   	label=ClientConfig
	labeljust=l
	fillcolor=white
	style=filled
   
   ClientConfig1708762283XXXqueueWithNamespace1134663318[
	label="+ queueWithNamespace()"
	style=filled
	fillcolor=white
	tooltip="ClientConfig

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2004609280 { 
   	label=DefaultMQPushConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumer633216551XXXearliestMsgStoreTime1134663318[
	label="+ earliestMsgStoreTime()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumer

&#10;  This method will be removed in a certain version after April 5, 2020, so please do not use this method.&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_290650472 { 
   	label=DefaultMQPushConsumerImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumerImpl1317777407XXXearliestMsgStoreTime1134663318[
	label="+ earliestMsgStoreTime()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumerImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_931339104 { 
   	label=MQClientAPIImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   MQClientAPIImpl1527982467XXXgetEarliestMsgStoretime1022730261[
	label="+ getEarliestMsgStoretime()"
	style=filled
	fillcolor=white
	tooltip="MQClientAPIImpl

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
DefaultMQPushConsumer633216551XXXearliestMsgStoreTime1134663318 -> ClientConfig1708762283XXXqueueWithNamespace1134663318;
DefaultMQPushConsumer633216551XXXearliestMsgStoreTime1134663318 -> DefaultMQPushConsumerImpl1317777407XXXearliestMsgStoreTime1134663318;
DefaultMQPushConsumerImpl1317777407XXXearliestMsgStoreTime1134663318 -> MQAdminImpl1527982467XXXearliestMsgStoreTime1134663318;
MQAdminImpl1527982467XXXearliestMsgStoreTime1134663318 -> MQClientAPIImpl1527982467XXXgetEarliestMsgStoretime1022730261;
MQAdminImpl1527982467XXXearliestMsgStoreTime1134663318 -> MQClientInstance700434529XXXfindBrokerAddressInPublish1808118735;
MQAdminImpl1527982467XXXearliestMsgStoreTime1134663318 -> MQClientInstance700434529XXXupdateTopicRouteInfoFromNameServer1808118735;
    
}
@enduml