@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#DefaultMQPushConsumer(String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1714486248 { 
   	label=rocketmq
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1115057354 { 
   	label=SqlFilterConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   SqlFilterConsumer819045724XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="SqlFilterConsumer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1195812458 { 
   	label=TagFilterConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   TagFilterConsumer819045724XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="TagFilterConsumer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_160577077 { 
   	label=Consumer
	labeljust=l
	fillcolor=white
	style=filled
   
   Consumer2031561881XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Consumer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2004609280 { 
   	label=DefaultMQPushConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735[
	label="+ DefaultMQPushConsumer()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumer

&#10;  Constructor specifying consumer group.&#10; &#10;  @param consumerGroup Consumer group.&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_325102424 { 
   	label=PushConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   PushConsumer1191250838XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="PushConsumer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_425376580 { 
   	label=ResponseConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   ResponseConsumer196752767XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="ResponseConsumer

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Consumer1014534777XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
Consumer1268842237XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
Consumer2031561881XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
Consumer382608349XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
PushConsumer1191250838XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
PushConsumer255454115XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
ResponseConsumer196752767XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
SqlFilterConsumer819045724XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
TagFilterConsumer819045724XXXmain1859653459 -> DefaultMQPushConsumer633216551XXXDefaultMQPushConsumer1808118735;
    
}
@enduml