@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#suspend()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.rocketmq.client.consumer.DefaultMQPushConsumer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1714486248 { 
   	label=rocketmq
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1188440734 { 
   	label=MessageFormatter
	labeljust=l
	fillcolor=white
	style=filled
   
   MessageFormatter1066893677XXXformat1881684228[
	label="+ format()"
	style=filled
	fillcolor=white
	tooltip="MessageFormatter

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1350583147 { 
   	label=Slf4jLogger
	labeljust=l
	fillcolor=white
	style=filled
   
   Slf4jLogger2118845798XXXinfo1881684228[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="Slf4jLogger

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1833644171 { 
   	label=InnerLogger
	labeljust=l
	fillcolor=white
	style=filled
   
   InnerLogger1066893677XXXinfo1881684228[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="InnerLogger

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2004609280 { 
   	label=DefaultMQPushConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumer633216551XXXsuspend0[
	label="+ suspend()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumer

&#10;  Suspend pulling new messages.&#10; "
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_246761303 { 
   	label=Logger
	labeljust=l
	fillcolor=white
	style=filled
   
   Logger690443815XXXinfo1780628115[
	label="+ info()"
	style=filled
	fillcolor=white
	tooltip="Logger

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_290650472 { 
   	label=DefaultMQPushConsumerImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMQPushConsumerImpl1317777407XXXsuspend0[
	label="+ suspend()"
	style=filled
	fillcolor=white
	tooltip="DefaultMQPushConsumerImpl

null"
	fontcolor=darkgreen
];
} 
} 
} 

subgraph cluster_679248890 { 
   	label=openmessaging
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1292383980 { 
   	label=rocketmq
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1112861134 { 
   	label=PushConsumerImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   PushConsumerImpl725268464XXXsuspend0[
	label="+ suspend()"
	style=filled
	fillcolor=white
	tooltip="PushConsumerImpl

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
DefaultMQPushConsumer633216551XXXsuspend0 -> DefaultMQPushConsumerImpl1317777407XXXsuspend0;
DefaultMQPushConsumerImpl1317777407XXXsuspend0 -> InnerLogger1066893677XXXinfo1881684228;
DefaultMQPushConsumerImpl1317777407XXXsuspend0 -> Slf4jLogger2118845798XXXinfo1881684228;
InnerLogger1066893677XXXinfo1881684228 -> Logger690443815XXXinfo1780628115;
InnerLogger1066893677XXXinfo1881684228 -> MessageFormatter1066893677XXXformat1881684228;
PushConsumerImpl725268464XXXsuspend0 -> DefaultMQPushConsumer633216551XXXsuspend0;
    
}
@enduml